# Generated by Django 5.0.7 on 2024-08-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabeceraventas',
            fields=[
                ('consecutivo', models.IntegerField(db_column='Consecutivo', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('totalventa', models.IntegerField(db_column='TotalVenta')),
            ],
            options={
                'db_table': 'CabeceraVentas',
                'managed': False,
            },
        ),
    ]
