# Generated by Django 5.0.7 on 2024-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleventas',
            fields=[
                ('detalleid', models.AutoField(db_column='DetalleID', primary_key=True, serialize=False)),
                ('valorproducto', models.IntegerField(db_column='ValorProducto')),
                ('iva', models.IntegerField(db_column='IVA')),
            ],
            options={
                'db_table': 'DetalleVentas',
                'managed': False,
            },
        ),
    ]
