# Generated by Django 5.0.7 on 2024-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('valorventa', models.IntegerField(db_column='valorVenta')),
                ('isiva', models.BooleanField(db_column='IsIVA')),
                ('porcentajeiva', models.IntegerField(db_column='PorcentajeIVA')),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
    ]
