# Generated by Django 5.0.7 on 2024-08-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
